### ISSUE TITLE
How to work with files

### ISSUE THREAD

**Issue by AlejandroSalgadoRamirez** [octet-stream/object-to-form-data#34]
Hi, I want to know how to work with input files using `objectToFormData` method

**Comment by octet-stream** [comment]
objectToFormData treats every non-POJO and non-Array value as serializable value, meaning that it calls `FormData.set` or `FormData.append` with the value. This is how you can add a File, or Blob to FormData:

```ts
const field = "Some field"
const file = new File(["Test file content"], "test.txt", {type: "text/plain"})
const blob = new Blob(["Test blob content"])

const form = objectToFormData({file, blob, field})

form.get("file") // -> File
form.get("blob") // -> File
form.get("field") // -> Some field
```

Note that values serialization is handled by FormData, which accepts `File`, `Blob`, and `string` values. Anything else is stringified.

**Comment by octet-stream** [comment]
Updated documentation with files example usage, hope this helps.
