### ISSUE TITLE
Facing problem adding the package through pnpm 

### ISSUE THREAD

**Issue by ajfahim** [octet-stream/object-to-form-data#39]
$ pnpm add @octetstream/object-to-form-data
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/Fer-dom: Not Found - 404

This error happened while installing a direct dependency of C:\Projects\akaar-erp-frontend

Fer-dom is not in the npm registry, or you have no permission to fetch it.

No authorization header was set for the request.
Progress: resolved 62, reused 61, downloaded 0, added 0

**Comment by octet-stream** [comment]
My library have no dependencies, so I don't think your issue caused by its installation. try check out where this `fer-dom` comes from via `pnpm why fer-dom`

Also, I've installed my library in a fresh project, via pnpm and the installation succeeded.

**Comment by octet-stream** [comment]
Closing, because can't reproduce and no response from the author, and as I said there're no dependencies in my package, so the error should not me caused by its installation.
